### ISSUE TITLE
[Help] Self-Signed Certificate Error During Installation

### ISSUE THREAD

**Issue by bognar-dev** [onlook-dev/onlook#803]
#### Describe the problem you are experiencing
I'm experiencing an error related to a self-signed certificate in the certificate chain while trying to install dependencies for the onlook-dev/onlook repository. The error occurs specifically during the installation of the supabase package and halts the process. I have tried installing on three different devices, but the issue persists.

#### Error Details
```
RequestError: self-signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\Bognar.NiklasStefan\Downloads\onlook\node_modules\got\dist\source\core\index.js:970:111)
    at Object.onceWrapper (node:events:635:26)
    at ClientRequest.emit (node:events:532:35)
    at origin.emit (C:\Users\Bognar.NiklasStefan\Downloads\onlook\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket._finishInit (node:_tls_wrap:1078:8)
    at ssl.onhandshakedone (node:_tls_wrap:864:12)
```

#### Request for Help
- Could someone help me resolve this self-signed certificate error?
- Are there any specific configurations or steps I need to follow to bypass or fix this certificate issue?

Any guidance or steps to fix this issue would be greatly appreciated. Thank you!

**Comment by Kitenite** [comment]
I don't believe this is specific to Onlook. What I can infer from this is your current system is preventing network calls necessary to install npm packages. If you're using a company device, it may be a security configuration to be done with IT. Please let me know if this is not the case. 

You may be able to disable this SSL check for your npm but i do NOT recommend doing so without checking with your IT/sysadmin. 
```
npm config set strict-ssl false
```

Please lmk if this helps :)

**Comment by Kitenite** [comment]
Closing for inactivity. Please lmk if this persists :)
