### ISSUE TITLE
[bug] Cannot find module 'dns/promises'

### ISSUE THREAD

**Issue by davehibshman** [onlook-dev/onlook#852]
#### Cannot find module `dns/promises` on project startup
* Installed on Mac OS Sequoia 15.1.1
* Initially using Node 14.x
  * Upgraded to latest LTS 22.X and same issue still exists.
* Start up Onlook for 1st time
* Chose to `New Project`
* After step number 3 on the initial wizard opened the terminal and saw this message:
  ```
  Stopping terminal...
  Cleaning up...
  Stopped.
  Reverting legacy settings...
  Setting up...
  Running...
  
  > starter-15@0.1.0 dev /Users/davehibshman/test-app
  > next dev --turbopack
  
  internal/modules/cjs/loader.js:934
    throw err;
    ^

  Error: Cannot find module 'dns/promises'
  Require stack:
  - /Users/davehibshman/test-app/node_modules/next/dist/lib/helpers/get-online.js
  - /Users/davehibshman/test-app/node_modules/next/dist/lib/install-dependencies.js
  - /Users/davehibshman/test-app/node_modules/next/dist/cli/next-test.js
  - /Users/davehibshman/test-app/node_modules/next/dist/bin/next
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
      at /Users/davehibshman/test-app/node_modules/next/dist/server/require-hook.js:55:36
      at Function.Module._load (internal/modules/cjs/loader.js:774:27)
      at Module.require (internal/modules/cjs/loader.js:1003:19)
      at Module.mod.require (/Users/davehibshman/test-app/node_modules/next/dist/server/require-hook.js:65:28)
      at require (internal/modules/cjs/helpers.js:107:18)
      at Object.<anonymous> (/Users/davehibshman/test-app/node_modules/next/dist/lib/helpers/get-online.js:12:58)
      at Module._compile (internal/modules/cjs/loader.js:1114:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
      at Module.load (internal/modules/cjs/loader.js:979:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/davehibshman/test-app/node_modules/next/dist/lib/helpers/get-online.js',
      '/Users/davehibshman/test-app/node_modules/next/dist/lib/install-dependencies.js',
      '/Users/davehibshman/test-app/node_modules/next/dist/cli/next-test.js',
      '/Users/davehibshman/test-app/node_modules/next/dist/bin/next'
    ]
  }
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! starter-15@0.1.0 dev: `next dev --turbopack`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the starter-15@0.1.0 dev script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /Users/davehibshman/.npm/_logs/2024-12-05T20_30_20_086Z-debug.log
  ```

**Comment by Kitenite** [comment]
Hmm weird, seems like some modules didn't install correctly. Could you share the log of running `npm install` on `/Users/davehibshman/test-app` @davehibshman?

```
cd /Users/davehibshman/test-app && npm i
```

**Comment by davehibshman** [comment]
@Kitenite Npm Install log attached.
```
davehibshman@davehibshman-mac test-app % npm i|tee npm-install.log
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

> sharp@0.33.5 install /Users/davehibshman/test-app/node_modules/sharp
> node install/check

sharp: Detected Rosetta, skipping search for globally-installed libvips
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for next@15.0.3: wanted: {"node":"^18.18.0 || ^19.8.0 || >= 20.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: next@15.0.3
npm WARN notsup Unsupported engine for sharp@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: sharp@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@15.0.3 (node_modules/next/node_modules/@next/swc-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@15.0.3: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-gnu@15.0.3 (node_modules/next/node_modules/@next/swc-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-gnu@15.0.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-musl@15.0.3 (node_modules/next/node_modules/@next/swc-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-musl@15.0.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@15.0.3 (node_modules/next/node_modules/@next/swc-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@15.0.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@15.0.3 (node_modules/next/node_modules/@next/swc-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@15.0.3: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@15.0.3 (node_modules/next/node_modules/@next/swc-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@15.0.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@15.0.3 (node_modules/next/node_modules/@next/swc-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@15.0.3: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linux-arm@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linux-arm@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linux-arm@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linux-arm@0.33.5: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-wasm32@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-wasm32@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-wasm32@0.33.5 (node_modules/sharp/node_modules/@img/sharp-wasm32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-wasm32@0.33.5: wanted {"os":"any","arch":"wasm32"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linux-x64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linux-x64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linux-x64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linux-x64@0.33.5: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-win32-x64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-win32-x64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-win32-x64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-win32-x64@0.33.5: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-darwin-x64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-darwin-x64@0.33.5
npm WARN notsup Unsupported engine for @img/sharp-win32-ia32@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-win32-ia32@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-win32-ia32@0.33.5 (node_modules/sharp/node_modules/@img/sharp-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-win32-ia32@0.33.5: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linux-arm64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linux-arm64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linux-arm64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linux-arm64@0.33.5: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linux-s390x@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linux-s390x@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linux-s390x@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linux-s390x@0.33.5: wanted {"os":"linux","arch":"s390x"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-darwin-arm64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-darwin-arm64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-darwin-arm64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-darwin-arm64@0.33.5: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linuxmusl-x64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linuxmusl-x64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linuxmusl-x64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linuxmusl-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linuxmusl-x64@0.33.5: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @img/sharp-linuxmusl-arm64@0.33.5: wanted: {"node":"^18.17.0 || ^20.3.0 || >=21.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @img/sharp-linuxmusl-arm64@0.33.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-linuxmusl-arm64@0.33.5 (node_modules/sharp/node_modules/@img/sharp-linuxmusl-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-linuxmusl-arm64@0.33.5: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linux-x64@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linux-x64@1.0.4: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linux-arm@1.0.5 (node_modules/sharp/node_modules/@img/sharp-libvips-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linux-arm@1.0.5: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linux-arm64@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linux-arm64@1.0.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linux-s390x@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linux-s390x@1.0.4: wanted {"os":"linux","arch":"s390x"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-darwin-arm64@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-darwin-arm64@1.0.4: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linuxmusl-arm64@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-linuxmusl-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linuxmusl-arm64@1.0.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @img/sharp-libvips-linuxmusl-x64@1.0.4 (node_modules/sharp/node_modules/@img/sharp-libvips-linuxmusl-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @img/sharp-libvips-linuxmusl-x64@1.0.4: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN notsup Unsupported engine for @typescript-eslint/parser@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@8.17.0
npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@8.17.0
npm WARN notsup Unsupported engine for ts-api-utils@1.4.3: wanted: {"node":">=16"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: ts-api-utils@1.4.3
npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@8.17.0
npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@8.17.0
npm WARN notsup Unsupported engine for @typescript-eslint/utils@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/utils@8.17.0
npm WARN notsup Unsupported engine for @typescript-eslint/type-utils@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/type-utils@8.17.0
npm WARN notsup Unsupported engine for @typescript-eslint/types@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@8.17.0
npm WARN notsup Unsupported engine for eslint-visitor-keys@4.2.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@4.2.0
npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@8.17.0: wanted: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@8.17.0

added 376 packages from 362 contributors and audited 401 packages in 12.233s

139 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by davehibshman** [comment]
I should also mention I am running on a 2023 Apple Mac M2 Pro.

**Comment by davehibshman** [comment]
@Kitenite Still the same error message.

**Comment by Kitenite** [comment]
Thanks @davehibshman. Does it run from your command line if you run npm run dev? 
Also is this an Onlook-created project?

**Comment by davehibshman** [comment]
@Kitenite Same error with `npm run dev`.  It is an Onlook-created project.  It is not much of a project.  I just wanted to get Onlook up and running to check it out so on first start I chose `Create Project` and after the setup step when it started the project I saw this in the terminal output.

**Comment by Kitenite** [comment]
@davehibshman,
Sorry this hasn't happened before. Could you try cloning the starter template directly? Otherwise a new project by nextjs would work as well. This seems like something is wrong with running the React project itself. 

https://github.com/onlook-dev/starter-v1
or 
https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup

**Comment by Kitenite** [comment]
Closing for inactivity, pls reopen if this is still an issue
